server:
  port: 8761 #8761 8762

spring:
  application:
    name: producer
  cloud:
    nacos:
      discovery:
        server-addr: 10.1.144.111:8848
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
    service.name: producer